Test system
ITMO-meet/backend pull request #9
Opened 2024-11-06 15:09 UTC by graevsky

### Описание изменений
Добавлена система тестирования.

Эндпоинты позволяют:
- `get_test_info` - получать информацию о тесте по его `id`. Эндпоинт - `/tests/*test_id*`. 
Принимает (I) и возвращает (O):
  - (I) `test_id` - ID теста в БД
  - (O) Имя теста (`name`)
  - (O) Описание теста (`description`)
  - (O) Количество вопросов (`questions_count`)
- `start_test` - запускать тест по его `id`. Эндпоинт - `/tests/*test_id*/start`.
Принимает (I) и возвращает (O):
  - (I) `test_id` - ID теста в БД
  - (I) `StartTestRequest` - пейлод, содержащий `user_id` - ID пользователя в БД (ИСУ)
  - (O) `result_id` - ID формы в БД, в которой будет храниться результат
- `get_question` - получать вопрос по `test_id` и `question_number`. Эндпоинт - `/tests/*test_id*/question/*question_number`
Принимает (I) и возрващает (O):
  - (I) `test_id` - ID теста в БД
  - (I) `question_number` - номер вопроса в тесте
- `answer_question` - отвечать на вопрос. Эндпоинт - `/results/answer/672b784a83b2d056ec5991d2`.
Принимает (I) и возвращает (O):
  - (I) `result_id` - ID формы с результатом в БД
  - (I) `AnswerRequest` - пейлод, содержащий `question_index` - номер вопроса и `answer` - ответ на вопрос (от 0 до 6)
  - (O) `updated_answers` - обновленный список ответов на вопросы
- `complete_test` - завершить тест по ID формы с результатом. Эндпоинт - `/results/complete/*result_id*`.
Принимает (I) и возвращает (O):
  - (I) `result_id` - ID формы с результатом в БД
  - (O) `score` - результат теста. Считается, как (реальная сумма ответов)/(максимальная сумма ответов (количество вопросов*7)) 
- `get_current_answers` - возвращает текущие ответы и статус для конкретного результата по `result_id`. Эндпоинт - `/results/current_result/*result_id**/answers`.
Принимает (I) и возвращает (O):
  - (I) `result_id` - ID результата в БД
  - (O) `answers - текущие ответы для данного результата
  - (O) `status` - завершен ли тест (true/false)
  
### Зачем нужны эти изменения?
Нужны для реализации тестовой подсистемы.

### Чек-лист
- [x] Я проверил(-а) изменения в локальной среде
- [x] Я добавил(а) тесты, чтобы покрыть свои изменения
- [x] Все существующие и новые тесты проходят успешно

2024-11-06 18:24 UTC, OverFitted commented
LGTM

2024-11-06 18:58 UTC, OverFitted requested changes
NIT, тесты не смотрел, по init_db NACK

2024-11-06 18:58 UTC, OverFitted commented on .github/workflows/ci.yml
> +      - feat/*
Стоит наверное ограничить, что конкретно будет в CI для feat

2024-11-06 18:58 UTC, OverFitted commented on .github/workflows/ci.yml
>      env:
.env лучше вынести, чтобы избежать дублирования кода

2024-11-06 18:58 UTC, OverFitted commented on app/models/pyObject.py
> +class PyObjectId(ObjectId):
chatGPT 🤓

2024-11-06 18:58 UTC, OverFitted commented on app/utils/db.py
> +db_instance = Database()
Лучше конечно так не делать. Хочешь singleton - пиши нормально класс

2024-11-06 18:58 UTC, OverFitted commented on init_db/create_result.py
Не очень в целом понимаю, зачем этот файл. Это базовый тест? Или это просто не убранный легаси код?

2024-11-06 18:58 UTC, OverFitted commented on init_db/create_result.py
В целом такой вопрос ко всей папке. Если это (как по названию) какая-то миграция БД, то лучше это делать не так, а хотя бы через парсер json

2024-11-06 18:58 UTC, OverFitted commented on requirements.txt
[pymongo](https://github.com/mongodb/mongo-python-driver) лучше обновить, если возможно

2024-11-06 19:01 UTC, graevsky commented on .github/workflows/ci.yml
> +      - feat/*
Конкретный фит указать ты имеешь в виду?

2024-11-06 19:01 UTC, graevsky commented on .github/workflows/ci.yml
>      env:
ci по диагонали писался из того, что было :)

2024-11-06 19:01 UTC, graevsky commented on app/models/pyObject.py
> +class PyObjectId(ObjectId):
да, вопросы?

2024-11-06 19:02 UTC, graevsky commented on app/utils/db.py
> +db_instance = Database()
мб перепишу :)

2024-11-06 19:02 UTC, graevsky commented on init_db/create_result.py
это я для себя написал, чтоб заполнить бдшку, чтоб постманом погонять, можно вообще по идее выкинуть

2024-11-06 19:02 UTC, graevsky commented on requirements.txt
у меня это ломало какую то из зависимостей:) Вроде motor

2024-11-06 19:03 UTC, OverFitted commented on .github/workflows/ci.yml
> +      - feat/*
Нет, не все проверки нужны на фит (если вообще нужны какие-то). Я бы выбрал конкретные обязательные и их бы юзал

2024-11-06 19:03 UTC, OverFitted commented on .github/workflows/ci.yml
> +      - feat/*
Почему это вообще в этом PR

2024-11-06 19:04 UTC, OverFitted commented on .github/workflows/ci.yml
>      env:
Вопрос сверху актуален

2024-11-06 19:04 UTC, OverFitted commented on init_db/create_result.py
Удалишь, останется NIT по сути, хотя по singleton пока вопросики конечно

2024-11-06 19:05 UTC, OverFitted commented
Чет грязненько получилось 😞

2024-11-06 21:39 UTC, graevsky commented on .github/workflows/ci.yml
> +      - feat/*
потому что я в этом пр понял, что ci не работает :)

2024-11-08 10:13 UTC, OverFitted submitted a review, later dismissed

2024-11-08 10:35 UTC, merged